<div class="container">

	<div class="jumbotron">
		<h1>
			<p class="text-justify">Welcome to list of Student's Profile</p>
		</h1>
	</div>
	<div class="row">
		<div class="col-md-12 text-right">
			<input type="text" name="search"> <a class="btn btn-info btn-xs"
				href="<?php echo $this->url('logout'); ?>" role="button"><span
				class="glyphicon glyphicon-search"></span>Search</a>
		</div>
	</div>
	<div class="row"></div>
	<div class="panel panel-success">
		<div class="panel-heading">List student's profile</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-md-12 text-right">
					<a class="btn btn-success btn-md"
						href="<?php echo $this->url('student', ['action'=>'add']); ?>"
						role="button"><span class="glyphicon glyphicon-plus"></span>Add</a>
				</div>
			</div>
			<table class="table table-hover">
				<thead>
					<tr>
						<td>ID</td>
						<td>FullName</td>
						<td>Address</td>
						<td>Phonenumber</td>
						<td>Function</td>
					</tr>
				</thead>

				<tbody>
					<?php foreach($students as $student):?>
					<tr>
						<td><a
							href="<?php echo $this->url('student', ['action'=>'get', 'id'=>$student->id]); ?>">
        				<?php echo $student->id; ?>
        			</a></td>
						<td>
        				<?php echo $student->fullName; ?>
        			</td>
						<td>
        				<?php echo $student->address; ?>
        			</td>
						<td>
        				<?php echo $student->phoneNumber; ?>
        			</td>
						<td>
							<div class="btn-group btn-group-sm">
								<a class="btn btn-info btn-xs"
									href="<?php echo $this->url('student', ['action'=>'edit', 'id'=>$student->id]); ?>"
									role="button"><span class="glyphicon glyphicon-wrench"></span>
									Edit</a> <a class="btn btn-danger btn-xs"
									href="<?php echo $this->url('student', ['action'=>'delete', 'id'=>$student->id]); ?>"
									role="button"><span class="glyphicon glyphicon-trash"></span>
									Delete</a>
							</div>
							</div>
						</td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>