<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
								
								echo $this->headMeta ()->appendName ( 'viewport', 'width=device-width, initial-scale=1.0' )->appendHttpEquiv ( 'X-UA-Compatible', 'IE=edge' )?>

        <!-- Le styles -->
        <?php
								
								echo $this->headLink ( array (
										'rel' => 'shortcut icon',
										'type' => 'image/vnd.microsoft.icon',
										'href' => $this->basePath () . '/img/favicon.ico' 
								) )->prependStylesheet ( $this->basePath () . '/css/style.css' )->prependStylesheet ( $this->basePath () . '/css/bootstrap-theme.min.css' )->prependStylesheet ( $this->basePath () . '/css/bootstrap.min.css' )?>

        <!-- Scripts -->
        <?php
								
								echo $this->headScript ()->prependFile ( $this->basePath () . '/js/bootstrap.min.js' )->prependFile ( $this->basePath () . '/js/jquery.min.js' )->prependFile ( $this->basePath () . '/js/respond.min.js', 'text/javascript', array (
										'conditional' => 'lt IE 9' 
								) )->prependFile ( $this->basePath () . '/js/html5shiv.js', 'text/javascript', array (
										'conditional' => 'lt IE 9' 
								) );
								?>

    </head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="<?php echo $this->url('home') ?>">Manager
					Student</a>
			</div>
			<ul class="nav navbar-nav">
				<li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
				<li class="dropdown"><a class="dropdown-toggle"
					data-toggle="dropdown" href="#"><?php echo $this->translate('Student	') ?> <span
						class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="<?php echo $this->url('student') ?>"><?php echo $this->translate('List') ?></a></li>
						<li><a href="#">Scores</a></li>
						<li><a href="#">Report</a></li>
					</ul></li>
				<li class="dropdown"><a class="dropdown-toggle"
					data-toggle="dropdown" href="#"><?php echo $this->translate('Profile') ?> <span
						class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="<?php echo $this->url('profile') ?>"><?php echo $this->translate('List profile') ?></a></li>
						<li><a href="<?php echo $this->url('profile') ?>/score">Score</a></li>
					</ul></li>
				<li><a href="<?php echo $this->url('api') ?>/get-scores">API</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
			<?php
			if ($user = $this->identity ()) {
				?>
				<li><a href="#"><span class="glyphicon glyphicon-user"></span> <?php echo $this->escapeHtml ( $user );?></a></li>
				<li><a href="<?php echo $this->url('logout'); ?>"><span
						class="glyphicon glyphicon-log-out"></span>Logout</a></li>
			<?php
			} else {?>
				<li><a href="#"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
			<?php 
			}
			?>
				

			</ul>
		</div>
	</nav>
	<div class="container">
            <?php echo $this->content; ?>
            <hr>
		<footer>
			<p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
		</footer>
	</div>
	<!-- /container -->
        <?php echo $this->inlineScript()?>
    </body>
</html>
